### ISSUE TITLE
Rename linkUrl to loginUrl

### ISSUE THREAD

**Issue by bobeagan** [synapsestudios/oidc-platform#319]
Maybe we should figure out how to make any of the public OIDC screens able to link to one another and and the private ones link to one another.  Same for emails?

**Comment by spruce-bruce** [comment]
I wouldn't mind doing a comprehensive audit of what's available on each screen and what _should_ be available on each screen.

When I wrote the theming stuff I did a quick pass trying to normalize as much as I could, but it's not quite _great_ yet. It's trickier than it seems, because there are often more than one workflow per screen. (ie, it's possible to link to the register screen from the client app _and_ from the login screen. If we always want to be able to show a login link on the register screen we need to make sure it receives and passes on all of the GET vars that the login screen requires. The register screen probably already does something like this, but it's the type of thing we'll need to think about for every screen)
