### ISSUE TITLE
let user in without needing to manually verify email address

### ISSUE THREAD

**Issue by syncolbysyn** [synapsestudios/oidc-platform#92]
As a user, when I create an account for a product/service, I want to be able to proceed directly to using that product/service without the inconvenience of loading my inbox and verifying my email (eg, via a link sent from the product/service)

- optional (per client/product/service); some products will still need manual email verification

TBDs
- [ ] if a product chooses to not force manual verification, are there routes to verify, or does the account expire after a certain time without verification, if verification is needed at all?

**Comment by spruce-bruce** [comment]
I need more info about what/why on this issue. On the face of it I'm opposed

**Comment by bobeagan** [comment]
Sounds like something that should be handled in the client

**Comment by spruce-bruce** [comment]
Especially with recent updates, this issue shouldn't be a thing.

From the perspective of the ID server we don't actually care about email verification (except when changing emails). Email verification is something that we provide as a service to client apps that they can choose to ignore.

We CAN raise the question, however, of whether or not it makes sense to be able to turn off verification emails because a client doesn't even ever want to send them, but I think that's different from what's being proposed here?
